In [3]:
import numpy as np
import time
import sys

In [5]:
s = range(1000)
print(sys.getsizeof(100))
print(len(s))
print(sys.getsizeof(4)*len(s))

28
1000
28000


In [7]:
p = np.arange(1000)
print(p.itemsize)
print(p.size)
print(p.size*p.itemsize)

8
1000
8000


In [13]:
SIZE = 1000000
L1 = range(SIZE)
L2 = range(SIZE)
start = time.time()
result = [(x,y) for x,y in zip(L1,L2)] # list of tuple of SIZE
print((time.time()-start)*1000)

145.8580493927002


In [14]:
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)
start = time.time()
result = A1+A2
print((time.time()-start)*1000)

51.94807052612305


In [16]:
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.size)
print(a.shape)

2
8
int64
6
(2, 3)


In [18]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
a = a.reshape(3,2)
print(a)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [21]:
print(a[0,1])
print(a[0:,1])
print(a[0:1,1])

2
[2 4 6]
[2]


In [26]:
a = np.linspace(1,10,4)
print(a)

[ 1.  4.  7. 10.]
