# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [10]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.86719737 0.60637567 0.14408614 0.74362284 0.83590232]
 [0.40927565 0.13616299 0.53503969 0.17582132 0.86985041]
 [0.52386551 0.0549992  0.59922782 0.04695566 0.08391784]
 [0.51080859 0.33192905 0.62776194 0.80776548 0.34194012]
 [0.73237008 0.80811929 0.5587043  0.61282078 0.80843071]]

[[ 0.97039139 -1.69069369 -1.42657277 -0.83405234 -0.29964714]
 [-1.08068071 -0.81629364  0.06264283  0.09108538 -0.80041883]
 [-0.53076813 -0.221841   -0.10229567 -0.05823318  0.01880008]
 [-0.20712121 -0.22819849  0.2360927  -0.89234939  0.10044719]
 [ 0.74028166  0.51911865  0.08026382  0.77773939 -0.1353489 ]
 [ 0.84705737  1.11026937 -1.55905001 -0.88210821  2.10111854]
 [ 1.50341347  0.65662915  0.21780362  0.91378603 -0.22795237]
 [-0.87121709 -2.6374445  -0.29516075  2.19210716 -0.2418202 ]
 [ 0.73023195 -0.71133774 -1.16987076  0.74699062  0.99014452]
 [ 0.08482309 -0.33032127 -0.87243517 -0.40003749  1.31653152]]


In [12]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5109180306369986
0.9414143593746063


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.04695565552423342
2.192107160659584


In [14]:
# break here for next video!

In [15]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.86269066 -0.27135463 -0.92471296  0.05604029 -1.14799456  2.99980045
 -1.95957149 -0.20968748 -0.23479469  1.58447068 -0.38100676 -0.98449877
  0.28595329  0.16116738  0.32552933  1.28212243 -1.07126812 -1.93450055
 -1.77276575]
-1.9595714857714015


In [16]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[-1.14799456  2.99980045 -1.95957149 -0.20968748 -0.23479469]


In [17]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 0.86269066  0.05604029 -1.95957149  1.58447068  0.28595329]


In [18]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.86719737 0.60637567 0.14408614 0.74362284 0.83590232]
 [0.40927565 0.13616299 0.53503969 0.17582132 0.86985041]
 [0.52386551 0.0549992  0.59922782 0.04695566 0.08391784]
 [0.51080859 0.33192905 0.62776194 0.80776548 0.34194012]
 [0.73237008 0.80811929 0.5587043  0.61282078 0.80843071]]
0.5350396854035203
0.5350396854035203


In [19]:
print(rand_mat[0:2,1:3])

[[0.60637567 0.14408614]
 [0.13616299 0.53503969]]


In [20]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 0.86269066 -0.27135463 -0.92471296  0.05604029 -1.14799456  2.99980045
 -1.95957149 -0.20968748 -0.23479469  1.58447068 -0.38100676 -0.98449877
  0.28595329  0.16116738  0.32552933  1.28212243 -1.07126812 -1.93450055
 -1.77276575]

[ 0.86269066 -0.27135463 -0.92471296  4.          4.          2.99980045
 -1.95957149 -0.20968748 -0.23479469  1.58447068 -0.38100676 -0.98449877
  0.28595329  0.16116738  0.32552933  1.28212243 -1.07126812 -1.93450055
 -1.77276575]

[ 0.86269066 -0.27135463 -0.92471296  1.          2.          2.99980045
 -1.95957149 -0.20968748 -0.23479469  1.58447068 -0.38100676 -0.98449877
  0.28595329  0.16116738  0.32552933  1.28212243 -1.07126812 -1.93450055
 -1.77276575]


In [21]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.86719737 0.60637567 0.14408614 0.74362284 0.83590232]
 [0.40927565 0.13616299 0.53503969 0.17582132 0.86985041]
 [0.52386551 0.0549992  0.59922782 0.04695566 0.08391784]
 [0.51080859 0.33192905 0.62776194 0.80776548 0.34194012]
 [0.73237008 0.80811929 0.5587043  0.61282078 0.80843071]]

[[0.86719737 0.60637567 0.14408614 0.74362284 0.83590232]
 [0.40927565 0.13616299 0.53503969 0.         0.        ]
 [0.52386551 0.0549992  0.59922782 0.         0.        ]
 [0.51080859 0.33192905 0.62776194 0.80776548 0.34194012]
 [0.73237008 0.80811929 0.5587043  0.61282078 0.80843071]]


In [22]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.86719737 0.60637567 0.14408614]
 [0.40927565 0.13616299 0.53503969]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [23]:
print(rand_mat)

[[3.         3.         3.         0.74362284 0.83590232]
 [3.         3.         3.         0.         0.        ]
 [0.52386551 0.0549992  0.59922782 0.         0.        ]
 [0.51080859 0.33192905 0.62776194 0.80776548 0.34194012]
 [0.73237008 0.80811929 0.5587043  0.61282078 0.80843071]]


In [24]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.74362284 0.83590232]
 [3.         3.         3.         0.         0.        ]
 [0.52386551 0.0549992  0.59922782 0.         0.        ]
 [0.51080859 0.33192905 0.62776194 0.80776548 0.34194012]
 [0.73237008 0.80811929 0.5587043  0.61282078 0.80843071]]


In [25]:
# break here for next video

In [26]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 0.07014389 -1.15976426  0.82292618  0.80829885  0.05692692  0.51378946
 -0.56597524  0.57364602  1.01147424  0.26639868  0.24526605  0.96480312
 -1.0610314  -1.24564598 -0.74538523]
[ True False  True  True  True  True False  True  True  True  True  True
 False False False]
[0.07014389 0.82292618 0.80829885 0.05692692 0.51378946 0.57364602
 1.01147424 0.26639868 0.24526605 0.96480312]


In [27]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 0.97039139 -1.69069369 -1.42657277 -0.83405234 -0.29964714]
 [-1.08068071 -0.81629364  0.06264283  0.09108538 -0.80041883]
 [-0.53076813 -0.221841   -0.10229567 -0.05823318  0.01880008]
 [-0.20712121 -0.22819849  0.2360927  -0.89234939  0.10044719]
 [ 0.74028166  0.51911865  0.08026382  0.77773939 -0.1353489 ]
 [ 0.84705737  1.11026937 -1.55905001 -0.88210821  2.10111854]
 [ 1.50341347  0.65662915  0.21780362  0.91378603 -0.22795237]
 [-0.87121709 -2.6374445  -0.29516075  2.19210716 -0.2418202 ]
 [ 0.73023195 -0.71133774 -1.16987076  0.74699062  0.99014452]
 [ 0.08482309 -0.33032127 -0.87243517 -0.40003749  1.31653152]]
[0.97039139 0.06264283 0.09108538 0.01880008 0.2360927  0.10044719
 0.74028166 0.51911865 0.08026382 0.77773939 0.84705737 1.11026937
 2.10111854 1.50341347 0.65662915 0.21780362 0.91378603 2.19210716
 0.73023195 0.74699062 0.99014452 0.08482309 1.31653152]


In [28]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[ 0.07014389 -1.15976426  0.82292618  0.80829885  0.05692692  0.51378946
 -0.56597524  0.57364602  1.01147424  0.26639868  0.24526605  0.96480312
 -1.0610314  -1.24564598 -0.74538523]

[ 0.07014389 -1.15976426 -5.         -5.          0.05692692 -5.
 -0.56597524 -5.         -5.          0.26639868  0.24526605 -5.
 -1.0610314  -1.24564598 -0.74538523]


In [30]:
x1 = np.arange(10)
y2 = np.sin(x1)
from tempfile import TemporaryFile
outfile = TemporaryFile()
np.savez(outfile, x=x1, y=y2)
_ = outfile.seek(0)
npzfile = np.load(outfile)
npzfile.files
npzfile['y']

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [31]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [32]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [33]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 0.97039139 -1.69069369 -1.42657277 -0.83405234 -0.29964714]
 [-1.08068071 -0.81629364  0.06264283  0.09108538 -0.80041883]
 [-0.53076813 -0.221841   -0.10229567 -0.05823318  0.01880008]
 [-0.20712121 -0.22819849  0.2360927  -0.89234939  0.10044719]
 [ 0.74028166  0.51911865  0.08026382  0.77773939 -0.1353489 ]
 [ 0.84705737  1.11026937 -1.55905001 -0.88210821  2.10111854]
 [ 1.50341347  0.65662915  0.21780362  0.91378603 -0.22795237]
 [-0.87121709 -2.6374445  -0.29516075  2.19210716 -0.2418202 ]
 [ 0.73023195 -0.71133774 -1.16987076  0.74699062  0.99014452]
 [ 0.08482309 -0.33032127 -0.87243517 -0.40003749  1.31653152]]



In [34]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.74362284 0.83590232]
 [3.         3.         3.         0.         0.        ]
 [0.52386551 0.0549992  0.59922782 0.         0.        ]
 [0.51080859 0.33192905 0.62776194 0.80776548 0.34194012]
 [0.73237008 0.80811929 0.5587043  0.61282078 0.80843071]]

[[ 0.97039139 -1.69069369 -1.42657277 -0.83405234 -0.29964714]
 [-1.08068071 -0.81629364  0.06264283  0.09108538 -0.80041883]
 [-0.53076813 -0.221841   -0.10229567 -0.05823318  0.01880008]
 [-0.20712121 -0.22819849  0.2360927  -0.89234939  0.10044719]
 [ 0.74028166  0.51911865  0.08026382  0.77773939 -0.1353489 ]
 [ 0.84705737  1.11026937 -1.55905001 -0.88210821  2.10111854]
 [ 1.50341347  0.65662915  0.21780362  0.91378603 -0.22795237]
 [-0.87121709 -2.6374445  -0.29516075  2.19210716 -0.2418202 ]
 [ 0.73023195 -0.71133774 -1.16987076  0.74699062  0.99014452]
 [ 0.08482309 -0.33032127 -0.87243517 -0.40003749  1.31653152]]
[[3.         3.         3.         0.74362284 0.83590232]
 [3.         3.    

In [35]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.74362284 0.83590232]
 [3.         3.         3.         0.         0.        ]
 [0.52386551 0.0549992  0.59922782 0.         0.        ]
 [0.51080859 0.33192905 0.62776194 0.80776548 0.34194012]
 [0.73237008 0.80811929 0.5587043  0.61282078 0.80843071]]

[[3.         3.         3.         0.74362284 0.83590232]
 [3.         3.         3.         0.         0.        ]
 [0.52386551 0.0549992  0.59922782 0.         0.        ]
 [0.51080859 0.33192905 0.62776194 0.80776548 0.34194012]
 [0.73237008 0.80811929 0.5587043  0.61282078 0.80843071]]
