# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding rows, columns, operating on 2d matrices aren't readily available. So, we will use *numpy* for such functions.



In [ ]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [ ]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Sum functions on np.array()

In [ ]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2, 4)
8
int64


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint:** You can also use **np.identity()** function ]

### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: **np.array()** function



### Question 3

Interchange both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**)

### Question 4
Add + 1 to all the elements in the given matrix.

Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function


### Question 6

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

### Array Slicing/Indexing:

- Now we'll learn to access multiple elements or a range of elements from an array.

In [ ]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Question 7

Print the array elements from start to 4th position


### Question 8

- Return elements from first position with step size 2. (Difference between consecutive elements is 2)

### Question 9

Reverse the array using array indexing:

### Question 10

- Create 3 x 3 array. Find the mean of the array and replace all the values above mean by 100