# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [10]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.87247701 0.23280561 0.37966397 0.48549622 0.71509266]
 [0.97970721 0.79009401 0.44483511 0.85494318 0.08011277]
 [0.01657601 0.24577272 0.01008251 0.01059923 0.30108359]
 [0.9350639  0.70351917 0.19293365 0.40922105 0.23320991]
 [0.37973059 0.52744986 0.35198727 0.60977189 0.47998122]]

[[-0.16647622  0.60619004  1.04371555  1.67468897  0.43064653]
 [-1.66266096 -0.08278658  0.59089703  0.03695263  0.12247359]
 [ 0.65480065 -0.37738775  0.34312795  1.77992028 -1.0200996 ]
 [-1.26971172 -0.34145866  0.6742134   0.60261082 -1.62053257]
 [-1.09535768  1.2044175  -0.79616625 -0.42418948  0.15265964]
 [ 1.8975049   0.14523218  0.55452857  1.17132845 -0.34640257]
 [ 1.58313713  1.30172588  0.32624692 -0.48479389 -0.04738471]
 [ 1.55244596 -0.27796091 -1.29944598  1.80678016  0.0081556 ]
 [-0.15232826 -1.35779307 -1.28194976  0.58645283 -0.01431238]
 [-1.41773255  0.74111519 -2.05080706 -0.33536513  0.36280606]]


In [12]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.44968841193656617
0.9910965077926105


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.010082505104520911
1.897504895991602


In [14]:
# break here for next video!

In [15]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 1.30215281 -0.31740771 -0.59642253 -0.26626513 -0.89985104  0.54311323
 -0.89677858  2.12008806  0.78834493 -1.42712343 -0.84662226  0.03852818
  0.94365334  0.05029534 -0.07310475 -1.30156209 -0.99779573  0.65236085
 -0.66263559]
-0.8967785761895719


In [16]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[-0.89985104  0.54311323 -0.89677858  2.12008806  0.78834493]


In [17]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 1.30215281 -0.26626513 -0.89677858 -1.42712343  0.94365334]


In [18]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.87247701 0.23280561 0.37966397 0.48549622 0.71509266]
 [0.97970721 0.79009401 0.44483511 0.85494318 0.08011277]
 [0.01657601 0.24577272 0.01008251 0.01059923 0.30108359]
 [0.9350639  0.70351917 0.19293365 0.40922105 0.23320991]
 [0.37973059 0.52744986 0.35198727 0.60977189 0.47998122]]
0.44483511011301324
0.44483511011301324


In [19]:
print(rand_mat[0:2,1:3])

[[0.23280561 0.37966397]
 [0.79009401 0.44483511]]


In [20]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 1.30215281 -0.31740771 -0.59642253 -0.26626513 -0.89985104  0.54311323
 -0.89677858  2.12008806  0.78834493 -1.42712343 -0.84662226  0.03852818
  0.94365334  0.05029534 -0.07310475 -1.30156209 -0.99779573  0.65236085
 -0.66263559]

[ 1.30215281 -0.31740771 -0.59642253  4.          4.          0.54311323
 -0.89677858  2.12008806  0.78834493 -1.42712343 -0.84662226  0.03852818
  0.94365334  0.05029534 -0.07310475 -1.30156209 -0.99779573  0.65236085
 -0.66263559]

[ 1.30215281 -0.31740771 -0.59642253  1.          2.          0.54311323
 -0.89677858  2.12008806  0.78834493 -1.42712343 -0.84662226  0.03852818
  0.94365334  0.05029534 -0.07310475 -1.30156209 -0.99779573  0.65236085
 -0.66263559]


In [21]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.87247701 0.23280561 0.37966397 0.48549622 0.71509266]
 [0.97970721 0.79009401 0.44483511 0.85494318 0.08011277]
 [0.01657601 0.24577272 0.01008251 0.01059923 0.30108359]
 [0.9350639  0.70351917 0.19293365 0.40922105 0.23320991]
 [0.37973059 0.52744986 0.35198727 0.60977189 0.47998122]]

[[0.87247701 0.23280561 0.37966397 0.48549622 0.71509266]
 [0.97970721 0.79009401 0.44483511 0.         0.        ]
 [0.01657601 0.24577272 0.01008251 0.         0.        ]
 [0.9350639  0.70351917 0.19293365 0.40922105 0.23320991]
 [0.37973059 0.52744986 0.35198727 0.60977189 0.47998122]]


In [22]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.87247701 0.23280561 0.37966397]
 [0.97970721 0.79009401 0.44483511]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [23]:
print(rand_mat)

[[3.         3.         3.         0.48549622 0.71509266]
 [3.         3.         3.         0.         0.        ]
 [0.01657601 0.24577272 0.01008251 0.         0.        ]
 [0.9350639  0.70351917 0.19293365 0.40922105 0.23320991]
 [0.37973059 0.52744986 0.35198727 0.60977189 0.47998122]]


In [24]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.48549622 0.71509266]
 [3.         3.         3.         0.         0.        ]
 [0.01657601 0.24577272 0.01008251 0.         0.        ]
 [0.9350639  0.70351917 0.19293365 0.40922105 0.23320991]
 [0.37973059 0.52744986 0.35198727 0.60977189 0.47998122]]


In [25]:
# break here for next video

In [26]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 0.53731784  0.82159948 -0.80983538 -0.09099873 -1.13571516 -0.0021156
 -1.61993282 -1.02069236  0.31053141 -0.68565304 -0.57714186 -0.60464853
  0.7832614  -0.42512296 -0.02492332]
[ True  True False False False False False False  True False False False
  True False False]
[0.53731784 0.82159948 0.31053141 0.7832614 ]


In [27]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-0.16647622  0.60619004  1.04371555  1.67468897  0.43064653]
 [-1.66266096 -0.08278658  0.59089703  0.03695263  0.12247359]
 [ 0.65480065 -0.37738775  0.34312795  1.77992028 -1.0200996 ]
 [-1.26971172 -0.34145866  0.6742134   0.60261082 -1.62053257]
 [-1.09535768  1.2044175  -0.79616625 -0.42418948  0.15265964]
 [ 1.8975049   0.14523218  0.55452857  1.17132845 -0.34640257]
 [ 1.58313713  1.30172588  0.32624692 -0.48479389 -0.04738471]
 [ 1.55244596 -0.27796091 -1.29944598  1.80678016  0.0081556 ]
 [-0.15232826 -1.35779307 -1.28194976  0.58645283 -0.01431238]
 [-1.41773255  0.74111519 -2.05080706 -0.33536513  0.36280606]]
[0.60619004 1.04371555 1.67468897 0.43064653 0.59089703 0.03695263
 0.12247359 0.65480065 0.34312795 1.77992028 0.6742134  0.60261082
 1.2044175  0.15265964 1.8975049  0.14523218 0.55452857 1.17132845
 1.58313713 1.30172588 0.32624692 1.55244596 1.80678016 0.0081556
 0.58645283 0.74111519 0.36280606]


In [28]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[ 0.53731784  0.82159948 -0.80983538 -0.09099873 -1.13571516 -0.0021156
 -1.61993282 -1.02069236  0.31053141 -0.68565304 -0.57714186 -0.60464853
  0.7832614  -0.42512296 -0.02492332]

[-5.00000000e+00 -5.00000000e+00 -8.09835376e-01 -9.09987260e-02
 -1.13571516e+00 -2.11560195e-03 -1.61993282e+00 -1.02069236e+00
  3.10531409e-01 -6.85653038e-01 -5.77141859e-01 -6.04648530e-01
 -5.00000000e+00 -4.25122956e-01 -2.49233219e-02]


In [46]:
x1 = np.arange(10)
y2 = np.sin(x)
from tempfile import TemporaryFile
outfile = TemporaryFile()
np.savez(outfile, x=x1, y=y2)
_ = outfile.seek(0)
npzfile = np.load(outfile)
npzfile.files
npzfile['y']

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [29]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [30]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [31]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-0.16647622  0.60619004  1.04371555  1.67468897  0.43064653]
 [-1.66266096 -0.08278658  0.59089703  0.03695263  0.12247359]
 [ 0.65480065 -0.37738775  0.34312795  1.77992028 -1.0200996 ]
 [-1.26971172 -0.34145866  0.6742134   0.60261082 -1.62053257]
 [-1.09535768  1.2044175  -0.79616625 -0.42418948  0.15265964]
 [ 1.8975049   0.14523218  0.55452857  1.17132845 -0.34640257]
 [ 1.58313713  1.30172588  0.32624692 -0.48479389 -0.04738471]
 [ 1.55244596 -0.27796091 -1.29944598  1.80678016  0.0081556 ]
 [-0.15232826 -1.35779307 -1.28194976  0.58645283 -0.01431238]
 [-1.41773255  0.74111519 -2.05080706 -0.33536513  0.36280606]]



In [32]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.48549622 0.71509266]
 [3.         3.         3.         0.         0.        ]
 [0.01657601 0.24577272 0.01008251 0.         0.        ]
 [0.9350639  0.70351917 0.19293365 0.40922105 0.23320991]
 [0.37973059 0.52744986 0.35198727 0.60977189 0.47998122]]

[[-0.16647622  0.60619004  1.04371555  1.67468897  0.43064653]
 [-1.66266096 -0.08278658  0.59089703  0.03695263  0.12247359]
 [ 0.65480065 -0.37738775  0.34312795  1.77992028 -1.0200996 ]
 [-1.26971172 -0.34145866  0.6742134   0.60261082 -1.62053257]
 [-1.09535768  1.2044175  -0.79616625 -0.42418948  0.15265964]
 [ 1.8975049   0.14523218  0.55452857  1.17132845 -0.34640257]
 [ 1.58313713  1.30172588  0.32624692 -0.48479389 -0.04738471]
 [ 1.55244596 -0.27796091 -1.29944598  1.80678016  0.0081556 ]
 [-0.15232826 -1.35779307 -1.28194976  0.58645283 -0.01431238]
 [-1.41773255  0.74111519 -2.05080706 -0.33536513  0.36280606]]
[[3.         3.         3.         0.48549622 0.71509266]
 [3.         3.    

In [33]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.48549622 0.71509266]
 [3.         3.         3.         0.         0.        ]
 [0.01657601 0.24577272 0.01008251 0.         0.        ]
 [0.9350639  0.70351917 0.19293365 0.40922105 0.23320991]
 [0.37973059 0.52744986 0.35198727 0.60977189 0.47998122]]

[[3.         3.         3.         0.48549622 0.71509266]
 [3.         3.         3.         0.         0.        ]
 [0.01657601 0.24577272 0.01008251 0.         0.        ]
 [0.9350639  0.70351917 0.19293365 0.40922105 0.23320991]
 [0.37973059 0.52744986 0.35198727 0.60977189 0.47998122]]
